# Generated by Django 6.0.1 on 2026-01-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('displayName', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('pinned', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('bestAvailability', models.DateTimeField(blank=True, null=True)),
                ('numParticipants', models.IntegerField(default=0)),
                ('numResponded', models.IntegerField(default=0)),
                ('numAvailable', models.IntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('participants', models.ManyToManyField(to='api.user')),
            ],
        ),
    ]
