# Generated by Django 6.0.1 on 2026-02-03 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_singledayavail_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='timeRangeEnd',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='timeRangeStart',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
