# Generated by Django 6.0.1 on 2026-02-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_duration_event_timerangeend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blockAdminAvail',
            field=models.BooleanField(default=False),
        ),
    ]
