# Generated by Django 6.0.1 on 2026-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_blockadminavail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='responseDeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sendReminder',
            field=models.BooleanField(default=False),
        ),
    ]
