# Generated by Django 6.0.1 on 2026-02-12 05:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_responsedeadline_event_sendreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timeslotMatrix',
            field=models.JSONField(default=api.models.default_matrix),
        ),
    ]
