import type { Event } from '../app/types/event';

export const DUMMY_EVENTS: Event[] = [
    { 
        id: '1', 
        title: 'emma bday',
        dateCreated: '',
        status: true,
        bestAvailability: null,
        participants: [''],
        numParticipants: 8,
        numAvailable: 5,
        tag: 'birthday',
        link: 'www.google.com',
        pinned: true,
        numResponded: 8
    },
    { 
        id: '2', 
        title: 'gnome bonanza',
        dateCreated: '',
        status: false,
        bestAvailability: '18 March 2026; 2:30PM',
        participants: [''],
        numParticipants: 7,
        numAvailable: 5,
        tag: 'gnomenanza',
        link: 'www.google.com',
        pinned: false,
        numResponded: 5
    },
    { 
        id: '3', 
        title: 'camping trip @ mt wilson',
        dateCreated: '',
        status: true,
        bestAvailability: '24 February 2026; 10:30AM',
        participants: [''],
        numParticipants: 20,
        numAvailable: 10,
        tag: 'friends',
        link: 'www.google.com',
        pinned: false,
        numResponded: 12
    },
    { id: '4',
        title: 'gnomenanza',
        dateCreated: '',
        status: false,
        bestAvailability: '5 April 2026; 8:00AM',
        participants: [''],
        numParticipants: 7,
        numAvailable: 5,
        tag: 'friends',
        link: 'www.google.com',
        pinned: false,
        numResponded: 7
    },
    { id: '5', 
        title: 'spring picnic',
        dateCreated: '',
        status: true,
        bestAvailability: '15 May 2026; 12:00PM',
        participants: [''],
        numParticipants: 20,
        numAvailable: 10,
        tag: 'friends',
        link: 'www.google.com',
        pinned: false,
        numResponded: 10
    },
    { id: '6', 
        title: 'board game night',
        dateCreated: '',
        status: false,
        bestAvailability: '2 June 2026; 6:30PM',
        participants: [''],
        numParticipants: 7,
        numAvailable: 5,
        tag: 'friends',
        link: 'www.google.com',
        pinned: false,
        numResponded: 6
    },
    { id: '7',
        title: 'art walk',
        dateCreated: '',
        status: true,
        bestAvailability: '9 July 2026; 4:00PM',
        participants: [''],
        numParticipants: 9,
        numAvailable: 5,
        tag: 'date',
        link: 'www.google.com',
        pinned: false,
        numResponded: 9
    },
    { id: '8',
        title: 'movie marathon',
        dateCreated: '',
        status: false,
        bestAvailability: '21 August 2026; 9:00PM',
        participants: [''],
        numParticipants: 15,
        numAvailable: 9,
        tag: 'date',
        link: 'www.google.com',
        pinned: false,
        numResponded: 11
    },
]